<!doctype html><html lang=ja><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><meta http-equiv=x-ua-compatible content="IE=edge"><meta name=theme-color content="dark"><title>GKE 上にて Pythonで logger.info() を行うとCloud logging では stderr に保存され、すべてエラーになる問題への対処法 | Shunya Ueta</title><link rel=stylesheet href=/sass/main.min.1a3290acca8b3fc92df85ea9200859476d6c80d59009c89a749300f3ce7a7a67.css><script type=application/javascript>var doNotTrack=false;if(!doNotTrack){(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');ga('create','UA-39994406-11','auto');ga('send','pageview');}</script><meta property="og:title" content="GKE 上にて Pythonで logger.info() を行うとCloud logging では stderr に保存され、すべてエラーになる問題への対処法"><meta property="og:description" content="Python のアプリケーションで、Cloud logger にログを出力したいときに
 標準のPython logging モジュールを利用して、ログを出力する Python Cloud Logging package を使用する  上記の２つの方法があります。
不必要にパッケージを増やしたくはないので、1の標準モジュールでCloud Logger へ出力できないか試してみました。
標準のPython logging モジュールを試す 標準のlogging モジュールでログを出力したいときに
1 2 3 4 5 6  import logging logger = logging.getLogger(__name__) def hoge(): logger.info('logging Start 2021')   と、logging.info() を仕込んで、Cloud logger にログを出力してみると、logger.info() で出しているはずなのに、Cloud logger 上ではすべてエラーとして扱われてしまっています。
原因を特定するために、logger のログを見てみると logger.info() がすべて stderr標準エラーストリームへ出力されてしまっています。
1 2 3 4 5 6 7 8 9 10 11 12  { &#34;textPayload&#34;: &#34;2021-02-20 21:26:51,012 - root:predict:36 - INFO: logging Start\n&#34;, ."><meta property="og:type" content="article"><meta property="og:url" content="https://shunyaueta.com/posts/2021-03-03/"><meta property="og:image" content="https://shunyaueta.com/ogp.jpg"><meta property="article:published_time" content="2021-03-03T00:29:03+09:00"><meta property="article:modified_time" content="2021-11-29T10:57:41+09:00"><meta name=twitter:card content="summary_large_image"><meta name=twitter:image content="https://shunyaueta.com/ogp.jpg"><meta name=twitter:title content="GKE 上にて Pythonで logger.info() を行うとCloud logging では stderr に保存され、すべてエラーになる問題への対処法"><meta name=twitter:description content="Python のアプリケーションで、Cloud logger にログを出力したいときに
 標準のPython logging モジュールを利用して、ログを出力する Python Cloud Logging package を使用する  上記の２つの方法があります。
不必要にパッケージを増やしたくはないので、1の標準モジュールでCloud Logger へ出力できないか試してみました。
標準のPython logging モジュールを試す 標準のlogging モジュールでログを出力したいときに
1 2 3 4 5 6  import logging logger = logging.getLogger(__name__) def hoge(): logger.info('logging Start 2021')   と、logging.info() を仕込んで、Cloud logger にログを出力してみると、logger.info() で出しているはずなのに、Cloud logger 上ではすべてエラーとして扱われてしまっています。
原因を特定するために、logger のログを見てみると logger.info() がすべて stderr標準エラーストリームへ出力されてしまっています。
1 2 3 4 5 6 7 8 9 10 11 12  { &#34;textPayload&#34;: &#34;2021-02-20 21:26:51,012 - root:predict:36 - INFO: logging Start\n&#34;, ."></head><body class=dark><nav class=navbar><div class=container><div class=flex><div><a class=brand href=/><span class=emoji>🦅</span>
Shunya Ueta</a></div><div class=flex><a href=/articles/>All posts</a>
<button id=dark-mode-button></button></div></div></div></nav><main><div class=container><article><header class=article-header><div class=thumb><div><h1>GKE 上にて Pythonで logger.info() を行うとCloud logging では stderr に保存され、すべてエラーになる問題への対処法</h1><div class=post-meta><div>By on <time>2021.03.03</time> (Last updated:<time>2021.11.29</time>)</div><div class=tags><a href=/tags/gcp/>gcp</a></div></div></div></div></header></article><div class=article-post><p>Python のアプリケーションで、Cloud logger にログを出力したいときに</p><ol><li>標準のPython logging モジュールを利用して、ログを出力する</li><li>Python Cloud Logging package を使用する</li></ol><p>上記の２つの方法があります。</p><p>不必要にパッケージを増やしたくはないので、1の標準モジュールでCloud Logger へ出力できないか試してみました。</p><h2 id=標準のpython-logging-モジュールを試す>標準のPython logging モジュールを試す</h2><p>標準のlogging モジュールでログを出力したいときに</p><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre class=chroma><code><span class=lnt>1
</span><span class=lnt>2
</span><span class=lnt>3
</span><span class=lnt>4
</span><span class=lnt>5
</span><span class=lnt>6
</span></code></pre></td><td class=lntd><pre class=chroma><code class=language-python data-lang=python><span class=kn>import</span> <span class=nn>logging</span>

<span class=n>logger</span> <span class=o>=</span> <span class=n>logging</span><span class=o>.</span><span class=n>getLogger</span><span class=p>(</span><span class=vm>__name__</span><span class=p>)</span>

<span class=k>def</span> <span class=nf>hoge</span><span class=p>():</span> 
	<span class=n>logger</span><span class=o>.</span><span class=n>info</span><span class=p>(</span><span class=s1>&#39;logging Start 2021&#39;</span><span class=p>)</span>
</code></pre></td></tr></table></div></div><p>と、logging.info() を仕込んで、Cloud logger にログを出力してみると、logger.info() で出しているはずなのに、Cloud logger 上ではすべてエラーとして扱われてしまっています。</p><p>原因を特定するために、logger のログを見てみると logger.info() がすべて <code>stderr</code>標準エラーストリームへ出力されてしまっています。</p><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre class=chroma><code><span class=lnt> 1
</span><span class=lnt> 2
</span><span class=lnt> 3
</span><span class=lnt> 4
</span><span class=lnt> 5
</span><span class=lnt> 6
</span><span class=lnt> 7
</span><span class=lnt> 8
</span><span class=lnt> 9
</span><span class=lnt>10
</span><span class=lnt>11
</span><span class=lnt>12
</span></code></pre></td><td class=lntd><pre class=chroma><code class=language-bash data-lang=bash><span class=o>{</span>
  <span class=s2>&#34;textPayload&#34;</span>: <span class=s2>&#34;2021-02-20 21:26:51,012 - root:predict:36 - INFO:  logging Start\n&#34;</span>,
	...
  <span class=o>}</span>,
  <span class=s2>&#34;timestamp&#34;</span>: <span class=s2>&#34;2021-02-20T12:26:51.013213826Z&#34;</span>,
  <span class=s2>&#34;severity&#34;</span>: <span class=s2>&#34;ERROR&#34;</span>,
  <span class=s2>&#34;labels&#34;</span>: <span class=o>{</span>
	...
  <span class=o>}</span>,
  <span class=s2>&#34;logName&#34;</span>: <span class=s2>&#34;projects/.../logs/stderr&#34;</span>,
  <span class=s2>&#34;receiveTimestamp&#34;</span>: <span class=s2>&#34;2021-02-20T12:26:55.050911180Z&#34;</span>
<span class=o>}</span>
</code></pre></td></tr></table></div></div><p>そのため、明示的に標準出力へ出力先を変更してみました。</p><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre class=chroma><code><span class=lnt>1
</span><span class=lnt>2
</span><span class=lnt>3
</span><span class=lnt>4
</span><span class=lnt>5
</span><span class=lnt>6
</span><span class=lnt>7
</span><span class=lnt>8
</span><span class=lnt>9
</span></code></pre></td><td class=lntd><pre class=chroma><code class=language-python data-lang=python><span class=kn>import</span> <span class=nn>logging</span>
<span class=kn>import</span> <span class=nn>sys</span>

<span class=n>logger</span> <span class=o>=</span> <span class=n>logging</span><span class=o>.</span><span class=n>getLogger</span><span class=p>(</span><span class=vm>__name__</span><span class=p>)</span>
<span class=n>handler</span> <span class=o>=</span> <span class=n>logging</span><span class=o>.</span><span class=n>StreamHandler</span><span class=p>(</span><span class=n>sys</span><span class=o>.</span><span class=n>stdout</span><span class=p>)</span>
<span class=n>logger</span><span class=o>.</span><span class=n>addHandler</span><span class=p>(</span><span class=n>handler</span><span class=p>)</span>

<span class=k>def</span> <span class=nf>hoge</span><span class=p>():</span> 
	<span class=n>logger</span><span class=o>.</span><span class=n>info</span><span class=p>(</span><span class=s1>&#39;logging Start 2021&#39;</span><span class=p>)</span>
</code></pre></td></tr></table></div></div><p>これで解決できているはずと、Cloud Loggerを見てみると</p><p><img src=/posts/2021-03-03/images/clooudlogging_stderr.png alt="Cloud logging duplicate log in stderr and stdout"></p><p>なぜか、<code>stderr</code> への出力は残ったまま、<code>stdout</code>への出力が新たに増えました。このままでもINFO レベルでログは残せているので目的は達成できていますが、<code>stderr</code>への出力が残ってしまっているせいでCloud logger 上でエラーが発生しているようになり問題です。なので、これを避けるために２つ目の方法であるPython Cloud Logging package を利用してみます。 (というかパッケージをむやみに増やしたくないのだが利用せざるを得ない。)</p><h2 id=python-cloud-logging-package-を使用する>Python Cloud Logging package を使用する</h2><p>まず<a href=https://github.com/googleapis/python-logging>Python Client for Cloud Logging</a> のチュートリアルをすすめて行きます。</p><p>Cloud logging のPython package の<a href=https://github.com/googleapis/python-logging#quick-start>Quick Start</a> にてわかりやすく導入方法が紹介されています。ここで混乱しやすいのが、GCPの<a href=https://cloud.google.com/logging/docs/reference/libraries#cloud-console>Logging Client Libraries</a> のドキュメントではまずService Account を作って、<code>GOOGLE_APPLICATION_CREDENTIALS</code> を使用してCloud Logging の認証を行ってくださいと書かれています。</p><p>ですが、</p><ul><li><a href=https://googleapis.dev/python/google-api-core/latest/auth.html>GCP上でのVMでパッケージを使用するなら認証は必要ない</a> 。ただし、デフォルトのSAを使いたくない場合や、GCP外などで動かしたい場合はSAが必要</li></ul><p>と本元のパッケージのドキュメントでは書かれており、こちらのほうが誤解が少なくていいですね。(公式ドキュメントだと、SA作成時に <code>Project > Owner</code> を指定しろと書かれているんだけど、これって権限過多なのでは無いのだろうか??)</p><p>ちなみにGCP 上の認証過程はこちらのドキュメントが詳しく書かれているので、気になった方は御覧ください。</p><p><a href=https://cloud.google.com/docs/authentication/production>Authenticating as a service account</a></p><p>上記の認証仮定をまとめると</p><ol><li>GOOGLE_APPLICATION_CREDENTIALS を参照する</li><li>ADC (Application Default Credentials) が、コードに紐付けられているSAを使用する</li><li>ADCは各サービスのSAを利用する</li><li>1-3 が使用できなかった場合、認証エラーが発生する</li></ol><p>最終的にGKE上でCloud logging へログを出力するためには、
以下のコードで無事に <code>INFO</code> のログが<code>stderr</code> に吐き出されることなく、<code>stdout</code> のみに<code>INFO</code>として出力されるようになります。</p><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre class=chroma><code><span class=lnt> 1
</span><span class=lnt> 2
</span><span class=lnt> 3
</span><span class=lnt> 4
</span><span class=lnt> 5
</span><span class=lnt> 6
</span><span class=lnt> 7
</span><span class=lnt> 8
</span><span class=lnt> 9
</span><span class=lnt>10
</span><span class=lnt>11
</span><span class=lnt>12
</span></code></pre></td><td class=lntd><pre class=chroma><code class=language-python data-lang=python><span class=kn>import</span> <span class=nn>logging</span>
<span class=kn>import</span> <span class=nn>sys</span>
<span class=c1># NOTE: GKE ではCotainerEngineHandler が必要</span>
<span class=kn>from</span> <span class=nn>google.cloud.logging.handlers</span> <span class=kn>import</span> <span class=n>ContainerEngineHandler</span>

<span class=n>logger</span> <span class=o>=</span> <span class=n>logging</span><span class=o>.</span><span class=n>getLogger</span><span class=p>(</span><span class=vm>__name__</span><span class=p>)</span>
<span class=c1># NOTE: stream で stdout を指定する</span>
<span class=n>logger</span><span class=o>.</span><span class=n>addHandler</span><span class=p>(</span><span class=n>ContainerEngineHandler</span><span class=p>(</span><span class=n>name</span><span class=o>=</span><span class=vm>__name__</span><span class=p>,</span> <span class=n>stream</span><span class=o>=</span><span class=n>sys</span><span class=o>.</span><span class=n>stdout</span><span class=p>))</span>
<span class=c1># NOTE: ログが重複して出力されるので、propagate を切る</span>
<span class=n>logger</span><span class=o>.</span><span class=n>propagate</span> <span class=o>=</span> <span class=bp>False</span>

<span class=n>logger</span><span class=o>.</span><span class=n>info</span><span class=p>(</span><span class=s1>&#39;Hello Cloud Logging.&#39;</span><span class=p>)</span>
</code></pre></td></tr></table></div></div><h2 id=appendix>Appendix</h2><ul><li><a href=https://docs.python.org/3/howto/logging.html>https://docs.python.org/3/howto/logging.html</a></li><li><a href=https://cloud.google.com/logging/docs/setup/python>https://cloud.google.com/logging/docs/setup/python</a></li><li><a href=https://www.ai-shift.co.jp/techblog/1217>https://www.ai-shift.co.jp/techblog/1217</a></li><li><a href=https://stackoverflow.com/questions/48078051/duplicate-log-entries-with-google-cloud-stackdriver-logging-of-python-code-on-ku>https://stackoverflow.com/questions/48078051/duplicate-log-entries-with-google-cloud-stackdriver-logging-of-python-code-on-ku</a><ul><li>同じような質問があった</li></ul></li></ul></div><h2>See Also</h2><ul><li><a href=/posts/2019-10-03/>遅すぎる `pandas.read_gbq` を使わずに、Google BigQueryから高速にデータを読み込む</a></li><li><a href=/posts/2019-09-24/>How to connect the Google Compute Engine via Visual Studio Code</a></li></ul></div><div class=container><nav class="flex container suggested"><a rel=prev href=/posts/2021-02-21/ title="Previous post (older)"><span>Previous</span>
GKE でローリングアップデート後、ローカルからポートフォワードでリクエストを投げるとcurl: (52) Empty reply from server と返ってくるときの対処方法</a>
<a rel=next href=/posts/2021-03-05/ title="Next post (newer)"><span>Next</span>
2021年の目標</a></nav></div></main></main><footer class="footer flex"><section class=container><nav class=footer-links><a href=/index.xml>RSS</a></nav></section><script async src=/js/features.min.a94f58a30ad2560de728e080d87f75c60cf806fd1b3d5f4815f1a1a02c0d1859.js></script></footer></body></html>